services:
  app-dev:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.dev
    container_name: sismato-hackagua-app-dev
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - m2:/root/.m2
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/sismato
      QUARKUS_DATASOURCE_USERNAME: root
      QUARKUS_DATASOURCE_PASSWORD: root
      QUARKUS_HIBERNATE_ORM_SCHEMA_MANAGEMENT_STRATEGY: update
    ports:
      - "8080:8080"   
    depends_on:
      - db

  db:
    image: postgis/postgis:latest
    container_name: postgres_dev
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sismato
    ports:
      - "5432:5432"  # host 5433 -> container 5432
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "7001:80"   # pgAdmin dev em 7001
    depends_on:
      - db

volumes:
  m2:
  postgres_dev_data: